# Numpy Exercise for AI 240  - 10459          

Instructor- Dr. Uma Gajendragadkar

### Exercise 1.1 - If Numpy is not already installed then please install Numpy using below instruction
!pip install Numpy      

### Exercise 1.2 # Import Numpy package using below instruction 
import numpy as np

In [2]:
import numpy as np

### Exercise 1.3 ## Example Usage Read below example and execute the cell

data = np.array([1,2,3,4,5])

print(data)

print(len(data))

print(type(data))

print(data.shape)

In [5]:
data = np.array([1,2,3,4,5])
print(data)
print(len(data))
print(type(data))
print(data.shape)

[1 2 3 4 5]
5
<class 'numpy.ndarray'>
(5,)


### Exercise 1.4 Do all exercises from Lecture slides. Refer slides shared after the lecture.

In [3]:
arr = np.array([10, 20, 30, 40, 50])
print(arr)

[10 20 30 40 50]


Create 2-D arry

In [5]:
arr = np.array([[10, 20, 30], [40, 50, 60]])
print(arr)

[[10 20 30]
 [40 50 60]]


Array Indexing

In [6]:
# get the first element from an array
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])

10


Slice the array in Numpy

In [7]:
# slice elements from index 1 to index 5
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


Sort the arrray in Numpy

In [8]:
arr = np.array([30, 20, 40, 10])
print(np.sort(arr))

[10 20 30 40]


Sort the array alphabetically

In [9]:
arr = np.array(['kiwi', 'berry', 'pear'])
print(np.sort(arr))

['berry' 'kiwi' 'pear']


### Exercise 1.5 Searching Arrays - find method of numpy to search an element in array - You can google for the method

Find the indexes where the value is 9:


arr = np.array([3, 2, 14, 9, 10, 12])

In [15]:
arr = np.array([3, 2, 14, 9, 10, 12])
i = np.where(arr == 9)
print(i)

(array([3], dtype=int64),)


### Exercise 1.6 Join two arrays given below and print the result.

arr1 = np.array([9, 5, 8])

arr2 = np.array([55, 89, 76])

In [11]:
arr1 = np.array([9, 5, 8])
arr2 = np.array([55, 89, 76])
joined_array = np.array([arr1, arr2])
print(joined_array)

[[ 9  5  8]
 [55 89 76]]


### Save and submit your notebook in your Github account.